---
title: "Slides"
description: "College-slides van de IRTM- en ANLP-cursussen aan DACS, Universiteit Maastricht."
page-layout: full
toc: false
---

<div class="container py-5">

## College-slides

<p class="section-intro">De slides staan op GitHub, samen met de bijbehorende tutorials. Alle PDF's zijn direct te bekijken in de browser of te downloaden.</p>

<div class="slide-block">

### Agentic Conversational Search

<p class="course-meta">IRTM &mdash; DACS, Universiteit Maastricht &mdash; 2025&ndash;2026</p>

<table class="lecture-table">
<tr><td class="lec-num">01</td><td class="lec-title">Introductie</td><td class="lec-link"><a href="https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/IRTM%2001%20Introduction%202025-2026.pdf" target="_blank">Bekijk PDF &rarr;</a></td></tr>
<tr><td class="lec-num">02</td><td class="lec-title">Index- en query-optimalisaties</td><td class="lec-link"><a href="https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/IRTM%2002%20Information%20Retrieval%20Index%20and%20Query%20Optimizations%202025-2026.pdf" target="_blank">Bekijk PDF &rarr;</a></td></tr>
<tr><td class="lec-num">03</td><td class="lec-title">Relevantie</td><td class="lec-link"><a href="https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/IRTM%2003%20Information%20Retrieval%20Relevance%202025-2026.pdf" target="_blank">Bekijk PDF &rarr;</a></td></tr>
<tr><td class="lec-num">04</td><td class="lec-title">Kwaliteitsmeting (incl. tutorial)</td><td class="lec-link"><a href="https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/IRTM%2004%20Measuring%20Quality%20including%20Tutorial%202025-2026.pdf" target="_blank">Bekijk PDF &rarr;</a></td></tr>
<tr><td class="lec-num">06</td><td class="lec-title">Kennisgrafen bouwen uit tekst &mdash; Deel 1</td><td class="lec-link"><a href="https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/IRTM%2006%20Building%20Knowledge%20Graphs%20from%20Text%20-%20Part%201%20-%202025-2026.pdf" target="_blank">Bekijk PDF &rarr;</a></td></tr>
<tr><td class="lec-num">07</td><td class="lec-title">Kennisgrafen bouwen uit tekst &mdash; Deel 2</td><td class="lec-link"><a href="https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/IRTM%2007%20Building%20Knowledge%20Graphs%20from%20Text%20-%20Part%202%20-%202025-2026.pdf" target="_blank">Bekijk PDF &rarr;</a></td></tr>
<tr><td class="lec-num">08</td><td class="lec-title">Patronen detecteren en tekst ordenen &mdash; Deel 1</td><td class="lec-link"><a href="https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/IRTM%2008%20Detecting%20Patterns%20and%20Organizing%20Text%20-%20Part%201%20-%202025-2026.pdf" target="_blank">Bekijk PDF &rarr;</a></td></tr>
<tr><td class="lec-num">09</td><td class="lec-title">Patronen detecteren en tekst ordenen &mdash; Deel 2</td><td class="lec-link"><a href="https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/IRTM%2009%20Detecting%20Patterns%20and%20Organizing%20Text%20-%202%20-%202025-2026.pdf" target="_blank">Bekijk PDF &rarr;</a></td></tr>
<tr><td class="lec-num">10</td><td class="lec-title">Conversational Search &mdash; De Basis</td><td class="lec-link"><a href="https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/IRTM%2010%20Conversational%20Search%20-%20the%20Basics%202025-2026.pdf" target="_blank">Bekijk PDF &rarr;</a></td></tr>
<tr><td class="lec-num">11</td><td class="lec-title">Conversational Search &mdash; Feitelijk blijven</td><td class="lec-link"><a href="https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/IRTM%2011%20Conversational%20Search%20-%20Sticking%20to%20the%20facts%202025-2026.pdf" target="_blank">Bekijk PDF &rarr;</a></td></tr>
<tr><td class="lec-num">12</td><td class="lec-title">Conversational Search &mdash; Agentic Approaches</td><td class="lec-link"><a href="https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/12%20IRTM%20Conversational%20Search%20-%20Agentic%20Approaches%202025-2026.pdf" target="_blank">Bekijk PDF &rarr;</a></td></tr>
</table>

[Volledige lecture notes (PDF) &rarr;](https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/IRTM%20Lecture%20Notes%20Full%20V9%2020260219.pdf){target="_blank" .me-3}
[Cursussyllabus &rarr;](https://github.com/TextMiningUM/IRTM-Student/blob/main/Course%20Materials/Course%20syllabus%20IRTM%202025-2026.pdf){target="_blank" .me-3}
[Alle bestanden bekijken &rarr;](https://github.com/TextMiningUM/IRTM-Student/tree/main/Course%20Materials){target="_blank"}

</div>

<div class="coming-soon-block">

### Advanced Natural Language Processing

<p class="course-meta" style="font-style:normal;">ANLP &mdash; DACS, Universiteit Maastricht &mdash; 2026&ndash;2027</p>

De college-slides voor de ANLP-cursus worden momenteel toegevoegd. Bekijk de GitHub-repository voor de laatste aanvullingen.

[Bekijk Course Materials op GitHub &rarr;](https://github.com/TextMiningUM/ANLP-Student/tree/main/Course%20Materials){target="_blank" .btn .btn-primary style="font-style:normal;"}

</div>

</div>
